version: "3"

services:
  mariadb:
    container_name: aegea-db
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql:delegated

  blog:
    container_name: aegea-blog
    image: 13rom/aegea:${AEGEA_VERSION}
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    depends_on:
      - mariadb
    ports:
      - ${PORT}:80
    user: "${UID}:${GID}"
    volumes:
      - ./data/themes:/var/www/html/themes:delegated
      - ./data/pictures:/var/www/html/pictures:delegated
      - ./data/user:/var/www/html/user:delegated
