version: '2.3'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./data/mysql:/var/lib/mysql

  e2:
    build: .
    image: zebradil/docker-e2
    environment:
      - VIRTUAL_HOST
    links:
      - db
    ports:
      - ${PORT}:80
    volumes:
      - ./data/themes:/var/www/html/themes
      - ./data/pictures:/var/www/html/pictures
      - ./data/user:/var/www/html/user